# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('unit_price', models.IntegerField(default=400000)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=20)),
                ('receiver_company', models.CharField(max_length=20)),
                ('estimate_date', models.DateTimeField(verbose_name='published')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_reg_number', models.IntegerField()),
                ('corp_name', models.CharField(max_length=20)),
                ('tel', models.IntegerField()),
                ('ceo_name', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=80)),
                ('business_type', models.CharField(max_length=15)),
                ('business_item', models.CharField(max_length=15)),
            ],
        ),
    ]
